In [1]:
import numpy as np
import pandas as pd
from cmapPy.pandasGEXpress.parse import parse
from pathlib import Path

In [38]:
DATA_DIR = Path("./data")
BATCH1 = "2024_07_19_Batch1_normalized_feature_select_negcon_batch.gct"
BATCH2 = "2025_01_31_Batch2_normalized_feature_select_negcon_batch.gct"
BATCH3 = "2025_06_10_Batch3_normalized_feature_select_negcon_batch.gct"
BATCH4 = "2025_09_25_Batch4_normalized_feature_select_negcon_batch.gct"
BATCH5 = "2025_09_25_Batch5_normalized_feature_select_negcon_batch.gct"

In [36]:
def extract(path: Path):
    gct = parse(str(path))
    df = gct.data_df
    df = df.T
    print("Unique perturbations: ", gct.col_metadata_df["perturbation"].unique())
    return df, gct.col_metadata_df

In [32]:
# batch 1
batch1_df, batch1_metadata = extract(str(DATA_DIR / BATCH1))
batch1_df["label"] = batch1_metadata["perturbation"].apply(lambda x: 1 if x == "3F9KO" or x == "KO" else 0)

Unique perturbations:  ['5E5_WT' '3F9KO' 'WT' 'KO']

/opt/conda/lib/python3.11/site-packages/cmapPy/pandasGEXpress/parse_gct.py:251: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  row_metadata = row_metadata.apply(lambda x: pd.to_numeric(x, errors="ignore"))
/opt/conda/lib/python3.11/site-packages/cmapPy/pandasGEXpress/parse_gct.py:277: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  col_metadata = col_metadata.apply(lambda x: pd.to_numeric(x, errors="ignore"))

In [18]:
batch1_df.shape

(615, 480)

In [ ]:
batch1_df

Index(['SAMPLE_0', 'SAMPLE_1', 'SAMPLE_2', 'SAMPLE_3', 'SAMPLE_4', 'SAMPLE_5',
       'SAMPLE_6', 'SAMPLE_7', 'SAMPLE_8', 'SAMPLE_9',
       ...
       'SAMPLE_605', 'SAMPLE_606', 'SAMPLE_607', 'SAMPLE_608', 'SAMPLE_609',
       'SAMPLE_610', 'SAMPLE_611', 'SAMPLE_612', 'SAMPLE_613', 'SAMPLE_614'],
      dtype='object', name='cid', length=615)

In [40]:
batch2_df, batch2_metadata = extract(DATA_DIR / BATCH2)

Unique perturbations:  ['WT' nan 'SELENON_KO']

/opt/conda/lib/python3.11/site-packages/cmapPy/pandasGEXpress/parse_gct.py:251: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  row_metadata = row_metadata.apply(lambda x: pd.to_numeric(x, errors="ignore"))
/opt/conda/lib/python3.11/site-packages/cmapPy/pandasGEXpress/parse_gct.py:277: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  col_metadata = col_metadata.apply(lambda x: pd.to_numeric(x, errors="ignore"))

In [41]:
batch3_df, batch3_metadataa = extract(DATA_DIR / BATCH3)

Unique perturbations:  ['SELENON KO' 'WT']

/opt/conda/lib/python3.11/site-packages/cmapPy/pandasGEXpress/parse_gct.py:251: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  row_metadata = row_metadata.apply(lambda x: pd.to_numeric(x, errors="ignore"))
/opt/conda/lib/python3.11/site-packages/cmapPy/pandasGEXpress/parse_gct.py:277: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  col_metadata = col_metadata.apply(lambda x: pd.to_numeric(x, errors="ignore"))

In [42]:
batch4_df, batch4_metadata = extract(DATA_DIR / BATCH4)

Unique perturbations:  ['SELENON KO' 'WT']

/opt/conda/lib/python3.11/site-packages/cmapPy/pandasGEXpress/parse_gct.py:251: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  row_metadata = row_metadata.apply(lambda x: pd.to_numeric(x, errors="ignore"))
/opt/conda/lib/python3.11/site-packages/cmapPy/pandasGEXpress/parse_gct.py:277: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  col_metadata = col_metadata.apply(lambda x: pd.to_numeric(x, errors="ignore"))

In [33]:
# batch 5
batch5_df, batch5_metadata = extract(str(DATA_DIR / BATCH5))

Unique perturbations:  ['WT-Exon3' 'SELENON KO-Exon3' 'WT-Exon5' 'SELENON KO-Exon5']

/opt/conda/lib/python3.11/site-packages/cmapPy/pandasGEXpress/parse_gct.py:251: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  row_metadata = row_metadata.apply(lambda x: pd.to_numeric(x, errors="ignore"))
/opt/conda/lib/python3.11/site-packages/cmapPy/pandasGEXpress/parse_gct.py:277: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  col_metadata = col_metadata.apply(lambda x: pd.to_numeric(x, errors="ignore"))

In [34]:
batch5_df.head()

rid,Cells_AreaShape_Compactness,Cells_AreaShape_EulerNumber,Cells_AreaShape_FormFactor,Cells_AreaShape_Orientation,Cells_AreaShape_Zernike_1_1,Cells_AreaShape_Zernike_2_0,Cells_AreaShape_Zernike_3_1,Cells_AreaShape_Zernike_3_3,Cells_AreaShape_Zernike_4_0,Cells_AreaShape_Zernike_4_2,...,Nuclei_Texture_InfoMeas1_RNA_10_03_256,Nuclei_Texture_InfoMeas1_RNA_3_02_256,Nuclei_Texture_InfoMeas2_AGP_10_03_256,Nuclei_Texture_InfoMeas2_DNA_3_02_256,Nuclei_Texture_InfoMeas2_ER_10_03_256,Nuclei_Texture_InfoMeas2_Mito_10_03_256,Nuclei_Texture_SumAverage_DNA_10_03_256,Nuclei_Texture_SumVariance_AGP_3_00_256,Nuclei_Texture_SumVariance_Mito_10_00_256,Nuclei_Texture_SumVariance_RNA_3_03_256
cid,,,,,,,,,,,,,,,,,,,,,
SAMPLE_0,3.1509,-0.46041,-1.9838,1.77150,-0.84255,-3.5581,2.8916,-1.26290,1.39540,-0.43916,...,1.030900,-1.144400,-1.503600,0.79916,-2.059300,2.2658,-0.797910,-0.082851,1.76000,-1.164100
SAMPLE_1,2.7700,2.63340,-1.5833,-0.82196,-0.47032,-3.5982,2.7094,-0.92361,0.83612,-1.58620,...,0.482040,-0.039521,0.115450,1.62320,0.202180,2.1204,-0.062936,1.123700,1.26530,0.521230
SAMPLE_2,2.3967,2.63340,-1.3447,-0.93325,-1.57100,-3.4700,1.0573,-1.01920,1.33090,-0.95244,...,0.070728,-1.003800,-0.022882,0.93277,-1.122200,3.7751,-0.883870,1.130500,3.28720,-0.013901
SAMPLE_3,2.6341,2.63340,-1.6044,-2.34930,-1.56430,-3.8546,1.9893,-1.78650,1.57380,-0.62075,...,0.047608,-0.984510,0.686450,1.65110,0.192770,3.1308,0.031008,2.187000,2.40170,0.015300
SAMPLE_4,2.0129,1.51320,-1.2465,0.37190,-0.48917,-2.7142,1.5236,-0.38793,0.87760,-0.90426,...,0.714040,-0.543630,-0.049577,0.78406,-0.022834,1.6011,-0.554760,0.611620,0.85475,-0.372870

In [35]:
batch5_df.shape

(560, 482)

In [13]:
batch5_metadata["perturbation"].unique()

array(['WT-Exon3', 'SELENON KO-Exon3', 'WT-Exon5', 'SELENON KO-Exon5'],
      dtype=object)

In [39]:
batch4_df, batch4_metadata = extract(DATA_DIR / BATCH4)

Unique perturbations:  ['SELENON KO' 'WT']

/opt/conda/lib/python3.11/site-packages/cmapPy/pandasGEXpress/parse_gct.py:251: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  row_metadata = row_metadata.apply(lambda x: pd.to_numeric(x, errors="ignore"))
/opt/conda/lib/python3.11/site-packages/cmapPy/pandasGEXpress/parse_gct.py:277: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  col_metadata = col_metadata.apply(lambda x: pd.to_numeric(x, errors="ignore"))

In [25]:
batch1_df.index = "B1_" + batch1_df.index.astype(str)
batch5_df.index = "B5_" + batch5_df.index.astype(str)

combined_df = pd.concat([batch1_df, batch5_df], axis=0, ignore_index=False, sort=False)
combined_df

rid,Cells_AreaShape_BoundingBoxMaximum_X,Cells_AreaShape_Compactness,Cells_AreaShape_EulerNumber,Cells_AreaShape_FormFactor,Cells_AreaShape_Orientation,Cells_AreaShape_Solidity,Cells_AreaShape_Zernike_1_1,Cells_AreaShape_Zernike_2_0,Cells_AreaShape_Zernike_2_2,Cells_AreaShape_Zernike_3_1,...,Nuclei_Texture_InfoMeas1_DNA_3_02_256,Nuclei_Texture_InfoMeas1_Mito_10_01_256,Nuclei_Texture_InfoMeas1_RNA_10_03_256,Nuclei_Texture_InfoMeas2_AGP_10_03_256,Nuclei_Texture_InfoMeas2_ER_10_03_256,Nuclei_Texture_InfoMeas2_Mito_10_03_256,Nuclei_Texture_SumAverage_DNA_10_03_256,Nuclei_Texture_SumVariance_AGP_3_00_256,Nuclei_Texture_SumVariance_Mito_10_00_256,Nuclei_Texture_SumVariance_RNA_3_03_256
cid,,,,,,,,,,,,,,,,,,,,,
B1_SAMPLE_0,2.8990,3.24220,2.264700,-3.01150,2.607400,-1.8098,-5.44760,-3.7635,-1.3939,-2.52560,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
B1_SAMPLE_1,2.7636,2.43230,1.480800,-2.45430,1.770600,-1.9241,-2.89990,-3.6214,-1.3392,-0.00173,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
B1_SAMPLE_2,1.6274,3.07760,1.558000,-3.04760,0.487130,-3.7681,-4.27720,-3.0761,-1.6354,-0.53902,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
B1_SAMPLE_3,2.5451,1.82460,1.427000,0.74780,0.061375,-1.0435,-3.85340,-2.8678,-1.6089,-1.49940,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
B1_SAMPLE_4,2.1380,2.79820,1.488000,-1.18430,-1.738200,-1.7038,-3.04000,-3.6850,-1.8131,-2.85300,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
B5_SAMPLE_555,NaN,-0.62733,-0.449660,0.51976,1.026700,NaN,0.78459,1.4561,NaN,-0.35255,...,1.8358,-0.28038,0.67340,-2.5232,-3.3699,0.266290,0.57940,-3.3019,-0.56390,-0.67606
B5_SAMPLE_556,NaN,-0.67778,0.015506,0.57464,0.785490,NaN,0.49504,1.7480,NaN,-0.90525,...,2.6677,-0.21553,0.70329,-2.3297,-2.6208,-0.804710,0.58661,-2.9644,-0.81725,-1.54530
B5_SAMPLE_557,NaN,-0.69643,-0.511680,0.66330,-1.248000,NaN,0.30808,1.3196,NaN,-1.35620,...,1.3980,-0.13461,0.16584,-1.9056,-1.9464,-1.347200,0.34376,-2.8707,-1.74110,-1.26870
B5_SAMPLE_558,NaN,-0.64662,-0.480670,0.54484,0.281280,NaN,0.46660,1.3352,NaN,-0.74100,...,1.4084,-0.55380,0.20395,-2.0141,-2.5333,0.007884,0.51398,-2.3630,-0.33953,-0.51799
B5_SAMPLE_559,NaN,-0.78461,-0.569830,0.70602,-1.022600,NaN,0.19111,1.9172,NaN,-1.30810,...,1.9171,0.15346,0.96400,-2.8810,-3.2938,-1.323000,0.64372,-2.8491,-1.29910,-0.97973

In [20]:
combined_df.shape

(1175, 716)

In [27]:
combined_df.reset_index()
combined_df

rid,Cells_AreaShape_BoundingBoxMaximum_X,Cells_AreaShape_Compactness,Cells_AreaShape_EulerNumber,Cells_AreaShape_FormFactor,Cells_AreaShape_Orientation,Cells_AreaShape_Solidity,Cells_AreaShape_Zernike_1_1,Cells_AreaShape_Zernike_2_0,Cells_AreaShape_Zernike_2_2,Cells_AreaShape_Zernike_3_1,...,Nuclei_Texture_InfoMeas1_DNA_3_02_256,Nuclei_Texture_InfoMeas1_Mito_10_01_256,Nuclei_Texture_InfoMeas1_RNA_10_03_256,Nuclei_Texture_InfoMeas2_AGP_10_03_256,Nuclei_Texture_InfoMeas2_ER_10_03_256,Nuclei_Texture_InfoMeas2_Mito_10_03_256,Nuclei_Texture_SumAverage_DNA_10_03_256,Nuclei_Texture_SumVariance_AGP_3_00_256,Nuclei_Texture_SumVariance_Mito_10_00_256,Nuclei_Texture_SumVariance_RNA_3_03_256
cid,,,,,,,,,,,,,,,,,,,,,
B1_SAMPLE_0,2.8990,3.24220,2.264700,-3.01150,2.607400,-1.8098,-5.44760,-3.7635,-1.3939,-2.52560,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
B1_SAMPLE_1,2.7636,2.43230,1.480800,-2.45430,1.770600,-1.9241,-2.89990,-3.6214,-1.3392,-0.00173,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
B1_SAMPLE_2,1.6274,3.07760,1.558000,-3.04760,0.487130,-3.7681,-4.27720,-3.0761,-1.6354,-0.53902,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
B1_SAMPLE_3,2.5451,1.82460,1.427000,0.74780,0.061375,-1.0435,-3.85340,-2.8678,-1.6089,-1.49940,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
B1_SAMPLE_4,2.1380,2.79820,1.488000,-1.18430,-1.738200,-1.7038,-3.04000,-3.6850,-1.8131,-2.85300,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
B5_SAMPLE_555,NaN,-0.62733,-0.449660,0.51976,1.026700,NaN,0.78459,1.4561,NaN,-0.35255,...,1.8358,-0.28038,0.67340,-2.5232,-3.3699,0.266290,0.57940,-3.3019,-0.56390,-0.67606
B5_SAMPLE_556,NaN,-0.67778,0.015506,0.57464,0.785490,NaN,0.49504,1.7480,NaN,-0.90525,...,2.6677,-0.21553,0.70329,-2.3297,-2.6208,-0.804710,0.58661,-2.9644,-0.81725,-1.54530
B5_SAMPLE_557,NaN,-0.69643,-0.511680,0.66330,-1.248000,NaN,0.30808,1.3196,NaN,-1.35620,...,1.3980,-0.13461,0.16584,-1.9056,-1.9464,-1.347200,0.34376,-2.8707,-1.74110,-1.26870
B5_SAMPLE_558,NaN,-0.64662,-0.480670,0.54484,0.281280,NaN,0.46660,1.3352,NaN,-0.74100,...,1.4084,-0.55380,0.20395,-2.0141,-2.5333,0.007884,0.51398,-2.3630,-0.33953,-0.51799
B5_SAMPLE_559,NaN,-0.78461,-0.569830,0.70602,-1.022600,NaN,0.19111,1.9172,NaN,-1.30810,...,1.9171,0.15346,0.96400,-2.8810,-3.2938,-1.323000,0.64372,-2.8491,-1.29910,-0.97973